// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Capacity struct {
	ID       string `json:"id"`
	Capacity int    `json:"capacity"`
}

type Chip struct {
	ID        string  `json:"id"`
	Persons   []*User `json:"persons"`
	CreatedAt string  `json:"createdAt"`
	Password  string  `json:"password"`
}

type Container struct {
	ID        string      `json:"id"`
	Status    *Status     `json:"status"`
	Street    string      `json:"street"`
	CreatedAt string      `json:"createdAt"`
	UpdatedAt *string     `json:"updatedAt,omitempty"`
	CType     *CType      `json:"cType"`
	Position  *Position   `json:"position"`
	Capacity  []*Capacity `json:"capacity"`
}

type History struct {
	ID          string    `json:"id"`
	ContainerID string    `json:"containerID"`
	ChipID      string    `json:"chipID"`
	Day         string    `json:"day"`
	Date        string    `json:"date"`
	Time        string    `json:"time"`
	Used        string    `json:"used"`
	Volume      *Capacity `json:"volume"`
}

type Mutation struct {
}

type Position struct {
	Latitude  float64 `json:"latitude"`
	Longitude float64 `json:"longitude"`
}

type Query struct {
}

type Status struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type User struct {
	ID        string  `json:"id"`
	Chip      *Chip   `json:"chip"`
	Username  string  `json:"username"`
	FirstName *string `json:"firstName,omitempty"`
	LastName  *string `json:"lastName,omitempty"`
	Email     *string `json:"email,omitempty"`
	CreatedAt string  `json:"createdAt"`
	UpdatedAt *string `json:"updatedAt,omitempty"`
}

type CType struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
